In [37]:
import numpy as np

def phi(x):
    return 1 / (1+np.exp(-x))

def phi1(phi): # returns dphi/dx given phi(x)
    return phi*(1-phi)

class Node:
    def __init__(self,dimensions):
        self.w = 10*np.ones((1,dimensions))
    def evaluate(self, x):
        return phi( x @ self.w.T)
    def refine(self,x,yhat):
        y = self.evaluate(x)
        e = y - yhat
        print(self.w)
        print(sum(e**2))
        correction = (x.T @ (phi1(y)*e)).T
        self.w = self.w - 5*correction
    def calibrate(self, x, yhat, iterations):
        for counter in range(0,iterations):
            self.refine(x,yhat)
        
n = Node(3)
x = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
yhat = np.array([[0,0,0,1]]).T
n.calibrate(x,yhat,1000)
sum((n.evaluate(x) - yhat)**2)

[[10. 10. 10.]]
[2.9999092]
[[9.99977301 9.99999999 9.99999999]]
[2.99990918]
[[9.99954597 9.99999998 9.99999998]]
[2.99990916]
[[9.99931888 9.99999997 9.99999997]]
[2.99990914]
[[9.99909173 9.99999996 9.99999996]]
[2.99990912]
[[9.99886454 9.99999995 9.99999995]]
[2.99990909]
[[9.99863729 9.99999994 9.99999994]]
[2.99990907]
[[9.99840999 9.99999993 9.99999993]]
[2.99990905]
[[9.99818264 9.99999992 9.99999992]]
[2.99990903]
[[9.99795524 9.99999991 9.99999991]]
[2.99990901]
[[9.99772779 9.9999999  9.9999999 ]]
[2.99990899]
[[9.99750028 9.99999989 9.99999989]]
[2.99990897]
[[9.99727272 9.99999988 9.99999988]]
[2.99990895]
[[9.99704511 9.99999987 9.99999987]]
[2.99990893]
[[9.99681745 9.99999986 9.99999986]]
[2.99990891]
[[9.99658974 9.99999985 9.99999985]]
[2.99990889]
[[9.99636197 9.99999983 9.99999983]]
[2.99990887]
[[9.99613416 9.99999982 9.99999982]]
[2.99990885]
[[9.99590629 9.99999981 9.99999981]]
[2.99990883]
[[9.99567837 9.9999998  9.9999998 ]]
[2.9999088]
[[9.9954504  9.99999979

array([2.99988254])

In [ ]:
class Layer:
    def __init__(self,dimensions,classes):
        self.nodes = []
        for i in range(0,classes):
            self.nodes.append(Node(dimensions))
    
    def evaluate(self,x):
        y = np.empty((x.shape[0],0))
        for node in self.nodes:
            y = np.concatenate((y,node.evaluate(x)),axis=1)
        return y
    
    def calibrate(self,x,yhat,iterations):
        j=0
        for node in self.nodes:
            node.calibrate(x,yhat[0:,j:j+1],iterations)
            j=j+1
            
nn = Layer(3,3)
x = np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
yhat = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,1]]).T
nn.calibrate(x,yhat,100)
np.round(nn.evaluate(x)).astype(int) - yhat